# .github/workflows/release.yml
# Create binaries on each release
name: goreleaser

on:
  push:
    tags:
      - 'v*' # only version tags trigger a run

permissions:
  contents: write # so GoReleaser can create the GitHub Release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all tags so GoReleaser sees them
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
